project:
  type: website

website:
  title: "Orgulo.us"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/Shoklan
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: slate
    css: styles.css



